src/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/',include('polls.urls',namespace='polls'))
]

src/polls/urls.py
'''
Created on 2015-10-28

@author: Administrator
'''
from django.conf.urls import url
from . import views
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^query/$', views.QueryView.as_view(), name='query'), 
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<question_id>[0-9]+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^add/$', views.add, name='add'),
    url(r'^(?P<question_id>[0-9]+)/selectone/$', views.selectone, name='selectone'),
    url(r'^update/$', views.update, name='update'),
    url(r'^chart/$', views.chart, name='chart'),
    url(r'^tddiv/$', views.tddiv, name='tddiv'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login1/$', views.login1, name='login1'),
    url(r'^tddiv1/$', views.tddiv1, name='tddiv1'),
]

src/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
import time
from django.db import connection

# Create your models here.
class DefineManager(models.Manager):
    def findquestionall(self):
        cursor =connection.cursor()
        cursor.execute(""" select * from polls_question""")
#         return  cursor.fetchall()
        return [[row[0],row[1],row[2]] for row in cursor.fetchall()]
    def finddicall(self):
        cursor =connection.cursor()
        cursor.execute(""" select * from polls_question""")
        desc =cursor.description
#         return desc
        return [
                dict(zip([col[0] for col in desc],row)) for row in cursor.fetchall()
                 ]       
class Question(models.Model):
    def __unicode__(self):
        return self.question_test
    def was_published_recently(self):
        return self.pub_date >= timezone.now()-datetime.timedelta(days=1)
    question_test =models.CharField(max_length=200)
    pub_date =models.DateTimeField(default=datetime.datetime.now)
    objects =models.Manager()
    custom = DefineManager()
    
    

class Choice(models.Model):
    question =models.ForeignKey(Question)
    choice_text =models.CharField(max_length=200)
    votes =models.IntegerField(default=0)
    def __unicode__(self): 
        return self.choice_text


            

src/polls/views.py
#coding: utf-8
from datetime import time
from test.inspect_fodder2 import a
import time

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse, response
from django.shortcuts import get_object_or_404, render, get_list_or_404
from django.views import generic

from .models import Choice, Question
#coding: utf-8


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
# 
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})



class IndexView(generic.ListView):
    template_name='polls/index.html'
    context_object_name='latest_question_list'
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
class ResultsView(generic.DetailView):
    model =Question
    template_name ='polls/results.html'
def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
class QueryView(generic.ListView):
    template_name='polls/query.html'
    context_object_name='latest_question_list'
    def get_queryset(self):
        return Question.objects.all()
def delete(request, question_id):
    try:
        p = get_object_or_404(Question,pk=question_id)
    except (KeyError,Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'error_message': "You didn't select a choice.",
        })
    else:p.delete()
    return HttpResponseRedirect(reverse('polls:query'))
def add(request):
#     t1 =request.POST['pub_date']
#     t2=time.strptime(t1,'%Y-%m-%d %H:%M:%S')
#     pub_date=time.mktime(t2)
    s=Question(question_test=request.POST['question_test'])
    s.save()
    return HttpResponseRedirect(reverse('polls:query'))
def selectone(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'polls/selectone.html', context)
def update(request):
    question_id=request.POST['id']
    p = get_object_or_404(Question,pk=question_id)
    if(request.POST['question_test']!=None):
        p.question_test=request.POST['question_test']
        p.save()
        return HttpResponseRedirect(reverse('polls:query'))
def chart(request):
    question=Question.objects.all()
    ls=[]
    lh=[]
    for a in question:
        ls.append(a.id)
        lh.append(a.question_test.encode("utf-8"))
        
    context = {'ls': ls,'lh':lh,'question':question}
    return render(request, 'polls/chart.html',context)
def tddiv(request):
    question=Question.objects.all()
    ls=[]
    lh=[]
    lt=[]
    l4=[]
    l5=[]
    for a in question:
        ls.append(int(a.id))
        lh.append(a.question_test.encode("utf-8"))
        lt.append(a.pub_date)
        l4.append(int(a.id/1))
        l4.append(int(a.id/2))
        l4.append(int(a.id/3))
        l4.append(int(a.id/4))
        l5.append(l4)   
    context = {'ls': ls,'lh':lh,'question':question,'lt':lt,'l4':l4,'l5':l4}
    return render(request, 'polls/tddiv.html',context)
def login(request):
    return render(request,'polls/login.html')
def login1(request):
    if request.POST['name']=='admin' and request.POST['Password']=='000000':
        return HttpResponseRedirect(reverse('polls:query'))
    else:
        p=u'账号密码错误'.encode("utf-8")
        context={'p':p}
        return render(request, 'polls/login.html',context)
def tddiv1(request):
    question=Question.objects.all()
    ls=[]
    lh=[]
    lt=[]
    l4=[]
    l5=[]
    for a in question:
        ls.append(a.id)
        lh.append(a.question_test.encode("utf-8"))
        lt.append(a.pub_date)
        l4.append(a.id/1)
        l4.append(a.id/2)
        l4.append(a.id/3)
        l4.append(a.id/4)
        l5.append(l4)   
    context = {'ls': ls,'lh':lh,'question':question,'lt':lt,'l4':l4,'l5':l4}
    return render(request, 'polls/tddiv1.html',context)
        
    
    

src/polls/templates/polls/chart.html
{%extends 'polls/base.html'%}
{% load staticfiles %}
<meta Charset="utf-8">
{%block content%}
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main" style="height:400px"></div>
    <!-- ECharts单文件引入 -->
    <script src="{%static 'polls/build/dist/echarts.js'%}"></script>
    <script type="text/javascript">
        // 路径配置
        require.config({
            paths: {
                echarts: '{%static "polls/build/dist"%}'
            }
        });
        
        // 使用
        require(
            [
                'echarts',
                'echarts/chart/line' // 使用柱状图就加载bar模块，按需加载
            ],
            function (ec) {
                // 基于准备好的dom，初始化echarts图表
                var myChart = ec.init(document.getElementById('main')); 
                
                option = {
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['最高','最低']
    },
    toolbox: {
        show : true,
        orient: 'horizontal',      // 布局方式，默认为水平布局，可选为：
                                   // 'horizontal' ¦ 'vertical'
        x: 'right',                // 水平安放位置，默认为全图右对齐，可选为：
                                   // 'center' ¦ 'left' ¦ 'right'
                                   // ¦ {number}（x坐标，单位px）
        y: 'top',                  // 垂直安放位置，默认为全图顶端，可选为：
                                   // 'top' ¦ 'bottom' ¦ 'center'
                                   // ¦ {number}（y坐标，单位px）
        color : ['#1e90ff','#22bb22','#4b0082','#d2691e'],
        backgroundColor: 'rgba(0,0,0,0)', // 工具箱背景颜色
        borderColor: '#ccc',       // 工具箱边框颜色
        borderWidth: 0,            // 工具箱边框线宽，单位px，默认为0（无边框）
        padding: 5,                // 工具箱内边距，单位px，默认各方向内边距为5，
        showTitle: true,
        feature : {
            mark : {
                show : true,
                title : {
                    mark : '辅助线-开关',
                    markUndo : '辅助线-删除',
                    markClear : '辅助线-清空'
                },
                lineStyle : {
                    width : 1,
                    color : '#1e90ff',
                    type : 'dashed'
                }
            },
            dataZoom : {
                show : true,
                title : {
                    dataZoom : '区域缩放',
                    dataZoomReset : '区域缩放-后退'
                }
            },
            dataView : {
                show : true,
                title : '数据视图',
                readOnly: true,
                lang : ['数据视图', '关闭', '刷新'],
                optionToContent: function(opt) {
                    var axisData = opt.xAxis[0].data;
                    var series = opt.series;
                    var table = '<table style="width:100%;text-align:center"><tbody><tr>'
                                 + '<td>时间</td>'
                                 + '<td>' + series[0].name + '</td>'
                                 + '<td>' + series[1].name + '</td>'
                                 + '</tr>';
                    for (var i = 0, l = axisData.length; i < l; i++) {
                        table += '<tr>'
                                 + '<td>' + axisData[i] + '</td>'
                                 + '<td>' + series[0].data[i] + '</td>'
                                 + '<td>' + series[1].data[i] + '</td>'
                                 + '</tr>';
                    }
                    table += '</tbody></table>';
                    return table;
                }
            },
            magicType: {
                show : true,
                title : {
                    line : '动态类型切换-折线图',
                    bar : '动态类型切换-柱形图',
                    stack : '动态类型切换-堆积',
                    tiled : '动态类型切换-平铺'
                },
                type : ['line', 'bar', 'stack', 'tiled']
            },
            restore : {
                show : true,
                title : '还原',
                color : 'black'
            },
            saveAsImage : {
                show : true,
                title : '保存为图片',
                type : 'jpeg',
                lang : ['点击本地保存'] 
            },
            myTool : {
                show : true,
                title : '自定义扩展方法',
                icon : 'image://../asset/ico/favicon.png',
                onclick : function (){
                    alert('myToolHandler')
                }
            }
        }
    },
    calculable : true,
    dataZoom : {
        show : true,
        realtime : true,
        start : 20,
        end : 80
    },
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : function (){
                var list = [];
                for (var i = 1; i <= 30; i++) {
                    list.push('2013-03-' + i);
                }
                return list;
            }()
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'最高',
            type:'line',
            data:function (){
                var list = [];
                for (var i = 1; i <= 30; i++) {
                    list.push(Math.round(Math.random()* 30));
                }
                return list;
            }()
        },
        {
            name:'最低',
            type:'line',
            data:function (){
                var list = [];
                for (var i = 1; i <= 30; i++) {
                    list.push(Math.round(Math.random()* 10));
                }
                return list;
            }()
        }
    ]
};
                // 为echarts对象加载数据 
                myChart.setOption(option); 
            }
        );
    </script>
    {%endblock%}
  
 

src/polls/templates/polls/ddiv.html
{% load staticfiles %}
<meta Charset="utf-8">

<div id="main" style="height:400px"></div>
 <script src="{% static 'polls/build/dist/echarts.js' %}"></script>
	 <script type="text/javascript">
        
        require.config({
            paths: {
                echarts: '{% static 'polls/build/dist' %}' 
            }
        });

		  
        require(
            [
                'echarts',
                'echarts/chart/bar' 
            ],
            function (ec) {
                
                var myChart = ec.init(document.getElementById('main')); 
                
                var option = {
                    tooltip: {
                        show: true
                    },
                    legend: {
                        data:['ss']
                    },
                    xAxis : [
                        {   
                     
                        
                            type : 'category',
                            data :[{% for q in question %}
                                    "{{q.question_test}}",
                                  {%endfor%}
                                   
                                   ]
                        
                         
                        }
                    ],
                    yAxis : [
                        {
                            type : 'value'
                        }
                    ],
                    series : [
                        {
                            "name":"ss",
                            "type":"bar",
                            "data":{{ls}}
                            
                        }
                    ]
                };
        
                
                myChart.setOption(option); 
            }
        );
    </script>

src/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{%block content%}
<h1>{{question.question_text}}</h1>
{%if error_message%}<p><strong>{{error_essage}}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id%}" method="post">
{%csrf_token%}
{% for choice in question.choice_set.all%}
<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{%endfor%}
<input type="submit" value="Vote" />

</form>
{%endblock%}

src/polls/templates/polls/index.html
{%extends 'polls/base.html'%}
{%block content%}
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css'%}"/>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_test }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{%endblock%}

src/polls/templates/polls/login.html
{% load staticfiles %}
<meta Charset="utf-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<link href="{%static 'polls/AdminLTE/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css" />
<link href="{%static 'polls/AdminLTE/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css" />
<link href="{%static 'polls/AdminLTE/css/ionicons.min.css'%}" rel="stylesheet" type="text/css" />
<link href="{%static 'polls/AdminLTE/dist/css/AdminLTE.min.css'%}" rel="stylesheet" type="text/css" />
<link href="{%static 'polls/AdminLTE/dist/css/skins/skin-blue.min.css'%}" rel="stylesheet" type="text/css" />
<body class="login-page">
    <div class="login-box">
      <div class="login-logo">
        {{p}}
      </div><!-- /.login-logo -->
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <form action="{% url 'polls:login1' %}" method="post">
        {%csrf_token%}
          <div class="form-group has-feedback">
            <input type="text" class="form-control" name="name" />
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input type="password" class="form-control" name="Password" />
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-8">
              <div class="checkbox icheck">
                <label>
                  <input type="checkbox"> Remember Me
                </label>
              </div>
            </div><!-- /.col -->
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div><!-- /.col -->
          </div>
        </form>

        <div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
          <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
        </div><!-- /.social-auth-links -->

        <a href="#">I forgot my password</a><br>
        <a href="register.html" class="text-center">Register a new membership</a>

      </div><!-- /.login-box-body -->
    </div><!-- /.login-box -->

    <!-- jQuery 2.1.4 -->
    <script src="../../plugins/jQuery/jQuery-2.1.4.min.js" type="text/javascript"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="../../bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="../../plugins/iCheck/icheck.min.js" type="text/javascript"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script>
  </body>

    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 2.1.4 -->
    <script src="{%static 'polls/AdminLTE/plugins/jQuery/jQuery-2.1.4.min.js' %}" type="text/javascript"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{%static 'polls/AdminLTE/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- AdminLTE App -->
    <script src="{%static 'polls/AdminLTE/dist/js/app.min.js'%}" type="text/javascript"></script>

    <!-- Optionally, you can add Slimscroll and FastClick plugins.
          Both of these plugins are recommended to enhance the
          user experience. Slimscroll is required when using the
          fixed layout. -->
          
  </body>

src/polls/templates/polls/query.html
{% extends 'polls/base.html' %}
{% load staticfiles %}
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css'%}"/>
{%block content%}
<table align="right">
<form  method="post" action="{% url 'polls:add' %}" align="right">
{%csrf_token%}
    <tr>
      <td width="97" height="25">question_text</td>
      <td width="188" height="25"> 
        <input name="question_test" type="text">
      </td>
    </tr>
    <tr>
      <td width="97" height="25">pub_date</td>
      <td width="188" height="25"> 
      <input name="pub_date" type="text">
       </td>
    </tr>
        <td width="188" height="25"> 
        <input type="submit" name="Submit" value="add">
        </td>
        <td width="188" height="25"> 
        <input name="enews" type="hidden" value="kkk">
        </td>
    </tr>
</form>
</table>




 <section class="content">
          <div class="row">
            <div class="col-xs-12">
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Hover Data Table</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example2" class="table table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>question_id</th>
			            <th>question_test</th>
			            <th>pub_date</th>
			            <th>删除</th>
			            <th>修改</th>
			            </tr>
                      </tr>
                    </thead>
                    <tbody>
                    {% for q in latest_question_list %}
                     <tr>
		             <td>{{q.id}}</td>
		             <td>{{q.question_test}}</td>
		             <td>{{q.pub_date|date:"Y-m-d H:i:s"}}</td>
		             <td><a href="{% url 'polls:delete' q.id%}">delete</a></td>
		             <td><a href="{% url 'polls:selectone' q.id%}">update</a></td>
		             </tr> 
		             {% endfor %}
                    </tbody>
                    
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
               {% endblock %}

src/polls/templates/polls/results.html
{%extends 'polls/base.html'%}
{%block content%}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{%endblock%}

src/polls/templates/polls/selectone.html
{%extends 'polls/base.html'%}
{%block content%}
<table>
<form  method="post" action="{% url 'polls:update' %}">
{%csrf_token%}
    <tr>
      <td width="97" height="25">question_text</td>
      <td width="188" height="25"> 
        <input name="question_test" type="text" value="{{question.question_test}}">
      </td>
    </tr>
    <tr>
      <td width="97" height="25">pub_date</td>
      <td width="188" height="25"> 
      <input name="pub_date" type="text"  value="{{question.pub_date}}">
       </td>
    </tr>
        <td width="188" height="25"> 
        <input type="submit" name="Submit" value="update">
        </td>
        <td width="188" height="25"> 
        <input name="enews" type="hidden" value="kkk">
        </td>
    </tr>
    <tr>
       <td width="97 heigth="25">
         <input type="hidden" name="id" value="{{question.id}}">
       </td>
    </tr>
</form>
</table>
{%endblock%}